trigger:
- main

pool:
  vmImage: ubuntu-latest

variables:
  imageName: 'project5-app'
  acrLoginServer: 'project5acraiswarya.azurecr.io'
  imageTag: '$(Build.BuildId)'
  manifestRepo: 'github.com/aiswaryakaladharan/project5-manifest-repo.git'

steps:

- task: Docker@2
  displayName: Login to ACR
  inputs:
    command: login
    containerRegistry: 'project5-acr-connection'

- script: |
    docker buildx create --use

    docker buildx build \
      --platform linux/arm64 \
      -t $(acrLoginServer)/$(imageName):$(imageTag) \
      --push .
  displayName: Build and Push Image

- script: |
    git config --global user.email "azuredevops@example.com"
    git config --global user.name "Azure DevOps"

    git clone https://$(GITHUB_TOKEN)@$(manifestRepo) manifest-repo

    cd manifest-repo

    sed -i "s|image: .*|image: $(acrLoginServer)/$(imageName):$(imageTag)|g" deployment.yaml

    git add deployment.yaml

    git commit -m "Updated image tag"

    git push
  displayName: Update deployment.yaml using sed
